apigee_edge_teams.team_settings:
  type: config_object
  label: 'Team settings'
  mapping:
    entity_label_singular:
      type: label
      label: 'How to refer to a Team on the UI (singular)'
    entity_label_plural:
      type: label
      label: 'How to refer to a Team on the UI (plural)'
    cache_expiration:
      type: integer
    non_member_team_apps_visible_api_products:
      type: sequence
      sequence:
        type: string
    team_invitation_expiry_days:
      type: integer
      label: 'Number of days for team invitation expiry'
    team_invitation_email_existing:
      type: 'mail'
      label: 'Team invitation email for existing users'
    team_invitation_email_new:
      type: 'mail'
      label: 'Team invitation email for new users'

apigee_edge_teams.team_app_settings:
  type: config_object
  label: 'Team App settings'
  mapping:
    entity_label_singular:
      type: label
      label: 'How to refer to a Team App on the UI (singular)'
    entity_label_plural:
      type: label
      label: 'How to refer to a Team App on the UI (plural)'
    cache_expiration:
      type: integer
    required_base_fields:
      type: sequence
      sequence:
        type: string
    locked_base_fields:
      type: sequence
      sequence:
        type: string
    credential_lifetime:
      type: integer

apigee_edge_teams.team_role.*:
  type: config_entity
  label: 'Team Role config entity.'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    locked:
      type: boolean
      label: 'If a role is locked, it can not be removed'
    permissions:
      type: sequence
      label: 'Permissions'
      sequence:
        type: string
        label: 'Permission'

# Schema for the entity reference 'apigee_edge_teams:team_members' selection
# handler settings.
entity_reference_selection.apigee_edge_teams:team_members:
  type: entity_reference_selection.default
  label: 'Team member selection handler settings'
  mapping:
    filter:
      type: mapping
      label: 'Filter settings'
      mapping:
        type:
          type: string
          label: 'Filter by'
        role:
          type: sequence
          label: 'Restrict to the selected roles'
          sequence:
            type: string
            label: 'Role'
        team:
          label: 'Exclude team members of this team'
          type: integer
    include_anonymous:
      type: boolean
      label: 'Include the anonymous user in the matched entities.'

views.filter.team_invitation_status:
  type: views.filter.in_operator
