version: "3"

services:
  database:
    image: ${DB_IMAGE:-wodby/mariadb:10.2-3.1.3}
    container_name: "${COMPOSE_PROJECT_NAME:-my_project}_database"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_NAME:-drupal}
      MYSQL_USER: ${DB_USER:-drupal}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-drupal}
      POSTGRES_USER: ${DB_USER:-drupal}

  php:
    build:
      context: ..
      dockerfile: .travis/Dockerfile
      args:
        - PHP_IMAGE=${PHP_IMAGE:-wodby/drupal-php:7.1-dev-4.5.0}
    container_name: "${COMPOSE_PROJECT_NAME:-my_project}_php"
    environment:
      DB_HOST: ${DB_HOST:-database}
      DB_USER: ${DB_USER:-drupal}
      DB_PASSWORD: ${DB_PASSWORD-password}
      DB_NAME: ${DB_NAME:-drupal}
      DB_DRIVER: ${DB_DRIVER:-mysql}
      SIMPLETEST_BASE_URL: http://webserver
      SIMPLETEST_DB: ${DB_DRIVER:-mysql}://${DB_USER:-drupal}:${DB_PASSWORD-password}@${DB_HOST:-database}/${DB_NAME:-drupal}
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", { "chromeOptions": { "w3c": false } }, "http://webdriver:4444/wd/hub"]'
      BROWSERTEST_OUTPUT_DIRECTORY: "/mnt/files/log/simpletest"
      COMPOSER_AUTH: ${COMPOSER_AUTH:-}
    volumes:
      - codebase:/var/www/html
      - $HOME/.composer/cache/files:/home/wodby/.composer/cache/files

  webserver:
    image: ${WEBSERVER_IMAGE:-wodby/php-apache:2.4-3.0.5}
    container_name: "${COMPOSE_PROJECT_NAME:-my_project}_webserver"
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html/build
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/build
    volumes:
      - codebase:/var/www/html

  phpcs:
    image: mxr576/docker-phpcs
    container_name: "${COMPOSE_PROJECT_NAME:-my_project}_phpcs"
    volumes:
      - ../:/opt/drupal-module
      - codebase:/var/www/html
    depends_on:
      - php

  webdriver:
    image: selenium/standalone-chrome:3
    # Unfortunatelly its seems this image is not working at this moment.
    # https://www.drupal.org/project/drupalci_environments/issues/2978243
    # image: drupalci/webdriver-chromedriver:dev

volumes:
  codebase:
