version: "3"

services:
  database:
    environment:
      MYSQL_MAX_ALLOWED_PACKET: 512M
      MYSQL_WAIT_TIMEOUT: 28800
  php:
    volumes:
      - log:/mnt/files/log
    environment:
      DRUPAL_CORE: ${DRUPAL_CORE:-}
      DEPENDENCIES: ${DEPENDENCIES:-}
      # We can not pass these environment variables with `docker-compose run -e` until
      # this has not been improved. https://github.com/wodby/php/pull/21#issuecomment-361200733
      DRUPAL_MODULE_NAME: apigee_edge
      APIGEE_EDGE_AUTH_TYPE: ${APIGEE_EDGE_AUTH_TYPE}
      APIGEE_EDGE_ENDPOINT: ${APIGEE_EDGE_ENDPOINT}
      APIGEE_EDGE_USERNAME: ${APIGEE_EDGE_USERNAME}
      APIGEE_EDGE_PASSWORD: ${APIGEE_EDGE_PASSWORD}
      APIGEE_EDGE_ORGANIZATION: ${APIGEE_EDGE_ORGANIZATION}
      APIGEE_EDGE_TEST_LOG_DIR: "/mnt/files/log"
      # Suppress deprecation warnings.
      # https://api.drupal.org/api/drupal/vendor%21symfony%21phpunit-bridge%21DeprecationErrorHandler.php/8.5.x
      SYMFONY_DEPRECATIONS_HELPER: disabled
      THREADS: ${THREADS:-2}
      TEST_ROOT: ${TEST_ROOT:-modules/contrib/apigee_edge/tests}
      # We have to set this variable even if we set this to disabled, because
      # otherwise xDebug does not get enabled and we need that for code coverage
      # generation.
      PHP_XDEBUG: 0
  webserver:
    environment:
      APACHE_FCGI_PROXY_TIMEOUT: 180 # Just in case, wait more than usual in tests.

volumes:
  log:
